### ISSUE TITLE
TypeError: SimplePitchingSplit.__init__() got an unexpected keyword argument 'summary'

### ISSUE THREAD

**Issue by sertdfyguhi** [zero-sum-seattle/python-mlb-statsapi#214]
I tried running this code to get the game log of a player.
```py
import mlbstatsapi

mlb = mlbstatsapi.Mlb()

print(
    mlb.get_player_stats(
        450203, ["gameLog"], ["pitching"]
    )
)
```
and it printed this error:
```sh
Traceback (most recent call last):
  File "/Users/user/programming/mlb/main.py", line 11, in <module>
    mlb.get_player_stats(
  File "/opt/homebrew/lib/python3.12/site-packages/mlbstatsapi/mlb_api.py", line 2199, in get_player_stats
    splits = mlb_module.create_split_data(mlb_data.data['stats'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mlbstatsapi/mlb_module.py", line 115, in create_split_data
    split_data = return_splits(stat['splits'], stat_type, stat_group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mlbstatsapi/mlb_module.py", line 73, in return_splits
    splits.append(obj(**split))
                  ^^^^^^^^^^^^
  File "<string>", line 19, in __init__
  File "/opt/homebrew/lib/python3.12/site-packages/mlbstatsapi/models/stats/pitching.py", line 562, in __post_init__
    self.stat = SimplePitchingSplit(**self.stat)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SimplePitchingSplit.__init__() got an unexpected keyword argument 'summary'
```

Can anyone help me fix this issue? Thanks.

**Comment by KCNilssen** [comment]
@sertdfyguhi this should fix the missing attribute "summery" in pitching stats. Update to 0.5.22 to get the changes
